export default [
  "........................",
  "........................",
  "........................",
  ".....WWWWWWWWWW.........",
  "....WBBBBBBBBBBW........",
  "...WWWWWWWWWWWWW........",
  ".....SSSSSSSSSS.........",
  "....SSwwwwwwwwSS........",
  "...SSwBBBBBBBBwSS.......",
  "..SSwBBWWBBWWBBwSS......",
  "...SSwBWWBBWWBwSS.......",
  "....SSSSSSSSSSSS........",
  "........................",
  "........................",
];
