export default [
	"........................",
	"........................",
	"...........SS...........",
	"..........SmmSS.........",
	".........SmmmmmmSS......",
	"........SmmQQmmmmmmSS...",
	".......SmmQBBQmmmmmmS...",
	"......SmmQBrrBQmmmmS....",
	".....SmmQBrrrrBQmmS.....",
	"....SmmQBrrrrrrBQS......",
	"...SmmQBBBBBBBBQS.......",
	"..SmmQQQQQQQQQS.........",
	".SmmmmmmmmmmS...........",
	"..SSSSSSSSSS............",
	"........................",
	"........................",
];
