export default [
	"........................",
	"........................",
	"...........SS...........",
	".........SSmmS..........",
	"......SSmmmmmmS.........",
	"...SSmmmmmmQQmmS........",
	"...SmmmmmmQBBQmmS.......",
	"....SmmmmQBrrBQmmS......",
	".....SmmQBrrrrBQmmS.....",
	"......SQBrrrrrrBQmmS....",
	".......SQBBBBBBBBQmmS...",
	".........SQQQQQQQQQmmS..",
	"...........SmmmmmmmmmmS.",
	"............SSSSSSSSSS..",
	"........................",
	"........................",
];
