export default [
	"........................",
	"........................",
	"................SS......",
	"..............SSmmS.....",
	"............SSmmmmS.....",
	"..........SSmmQQmmS.....",
	"........SSmmQBBQmmS.....",
	"......SSmmQBrrBQmmS.....",
	"....SSmmQBrrrrBQmmS.....",
	"..SSmmQBrrrrrrBQmmS.....",
	".SmmQBBBBBBBBBBBBQmmS...",
	".SmmQQQQQQQQQQQQQQmmS...",
	"..SmmmmmmmmmmmmmmmmS.....",
	"...SSSSSSSSSSSSSSSS......",
	"........................",
	"........................",
];
